wallpaper {
    monitor = eDP-1
    path = /home/kauadev/.config/wallpapers/anime-girl-smoking-blue-eyes-hair-hd-wallpaper-uhdpaper.com-529@5@n.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/kauadev/.config/wallpapers/anime-girl-smoking-blue-eyes-hair-hd-wallpaper-uhdpaper.com-529@5@n.jpg
    fit_mode = cover
}

# Coringa — cobre VM e qualquer monitor não listado
wallpaper {
    monitor =
    path = /home/kauadev/.config/wallpapers/anime-girl-smoking-blue-eyes-hair-hd-wallpaper-uhdpaper.com-529@5@n.jpg
    fit_mode = cover
}

splash = false
ipc = off