require("lua.programs")
require("lua.monitors")
require("lua.variables")
require("lua.autostart")
require("lua.lookandfeel")
require("lua.layoutMiscInput")
require("lua.keybinds")
require("lua.workspaces")
