wallpaper {
    monitor = eDP-1
    path = /home/kauadev/.config/wallpapers/wallpaper.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/kauadev/.config/wallpapers/wallpaper.png
    fit_mode = cover
}

# Coringa — cobre VM e qualquer monitor não listado
wallpaper {
    monitor =
    path = /home/kauadev/.config/wallpapers/wallpaper.png
    fit_mode = cover
}

splash = false
ipc = off
